### ISSUE TITLE
Testing branch on linux fails on libr-bfd.c

### ISSUE THREAD

**Issue by dromer** [RomanKubiak/ctrlr#89]
On Debian Buster: 

```
ctrlr/Builds/LinuxMakefile$ ./build.sh -f
CTRLR[linux]: Building for x86_64, JOBS 12
CTRLR[linux]: Compile PCH
stadfx.h
stdafx_luabind.h
CTRLR[linux]: Build now

Compiling include_juce_audio_plugin_client_VST2.cpp
Compiling compat.c
Compiling core.c
Compiling darwin_usb.c
Compiling descriptor.c
Compiling enums.c
Compiling hotplug.c
Compiling io.c
Compiling linux_udev.c
Compiling linux_usbfs.c
Compiling poll_posix.c
Compiling poll_windows.c
Compiling strerror.c
Compiling structs.c
Compiling sync.c
Compiling threads_posix.c
Compiling threads_windows.c
Compiling usb.c
Compiling windows_usb.c
Compiling lua.c
Compiling class.cpp
Compiling class_registry.cpp
Compiling class_info.cpp
Compiling class_rep.cpp
Compiling create_class.cpp
Compiling error.cpp
Compiling exception_handler.cpp
Compiling function.cpp
Compiling function_introspection.cpp
Compiling inheritance.cpp
Compiling link_compatibility.cpp
Compiling lua51compat.cpp
Compiling object_rep.cpp
Compiling open.cpp
Compiling operator.cpp
Compiling pcall.cpp
Compiling scope.cpp
Compiling set_package_preload.cpp
Compiling shared_ptr_converter.cpp
Compiling stack_content_by_name.cpp
Compiling weak_ref.cpp
Compiling wrapper_base.cpp
Compiling keys.cpp
Compiling libr-bfd.c
../../Source/Misc/libr-bfd.c: In function ‘keep_symbol’:
../../Source/Misc/libr-bfd.c:112:28: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
     bfd_section_size(chkscn) == 0
                            ^
../../Source/Misc/libr-bfd.c:112:5: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
     bfd_section_size(chkscn) == 0
     ^~~~~~~~~~~~~~~~
     bfd_set_gp_size
../../Source/Misc/libr-bfd.c:112:5: note: each undeclared identifier is reported only once for each function it appears in
../../Source/Misc/libr-bfd.c: In function ‘setup_sections’:
../../Source/Misc/libr-bfd.c:169:25: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
    bfd_section_size(iscn) == 0
                         ^
../../Source/Misc/libr-bfd.c:169:4: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
    bfd_section_size(iscn) == 0
    ^~~~~~~~~~~~~~~~
    bfd_set_gp_size
../../Source/Misc/libr-bfd.c:197:5: error: too few arguments to function ‘bfd_set_section_size’
    !bfd_set_section_size(oscn, iscn->size)
     ^~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:30,
                 from ../../Source/Misc/libr-bfd.c:29:
/usr/include/bfd.h:1915:13: note: declared here
 bfd_boolean bfd_set_section_size
             ^~~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c:207:29: error: macro "bfd_section_vma" requires 2 arguments, but only 1 given
   vma = bfd_section_vma(iscn);
                             ^
../../Source/Misc/libr-bfd.c:207:9: error: ‘bfd_section_vma’ undeclared (first use in this function); did you mean ‘bfd_scan_vma’?
   vma = bfd_section_vma(iscn);
         ^~~~~~~~~~~~~~~
         bfd_scan_vma
../../Source/Misc/libr-bfd.c:213:5: error: too few arguments to function ‘bfd_set_section_vma’
    !bfd_set_section_vma(oscn, vma)
     ^~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:30,
                 from ../../Source/Misc/libr-bfd.c:29:
/usr/include/bfd.h:1686:1: note: declared here
 bfd_set_section_vma (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr, bfd_vma val)
 ^~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c:225:63: error: macro "bfd_section_alignment" requires 2 arguments, but only 1 given
    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
                                                               ^
../../Source/Misc/libr-bfd.c:225:37: error: ‘bfd_section_alignment’ undeclared (first use in this function); did you mean ‘bfd_set_section_alignment’?
    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
                                     ^~~~~~~~~~~~~~~~~~~~~
                                     bfd_set_section_alignment
../../Source/Misc/libr-bfd.c:225:5: error: too few arguments to function ‘bfd_set_section_alignment’
    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:30,
                 from ../../Source/Misc/libr-bfd.c:29:
/usr/include/bfd.h:1694:1: note: declared here
 bfd_set_section_alignment (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr,
 ^~~~~~~~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c: In function ‘build_output’:
../../Source/Misc/libr-bfd.c:301:31: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
   size = bfd_section_size(iscn);
                               ^
../../Source/Misc/libr-bfd.c:301:10: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
   size = bfd_section_size(iscn);
          ^~~~~~~~~~~~~~~~
          bfd_set_gp_size
../../Source/Misc/libr-bfd.c: In function ‘add_section’:
../../Source/Misc/libr-bfd.c:566:4: error: too few arguments to function ‘bfd_set_section_flags’
   !bfd_set_section_flags(scn, SEC_HAS_CONTENTS | SEC_DATA | SEC_IN_MEMORY)
    ^~~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:30,
                 from ../../Source/Misc/libr-bfd.c:29:
/usr/include/bfd.h:1899:13: note: declared here
 bfd_boolean bfd_set_section_flags
             ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:562: build/intermediate/Release/libr-bfd_fc7a9004.o] Error 1
make: *** Waiting for unfinished jobs....
CTRLR[linux]: build failed

```

**Comment by RomanKubiak** [comment]
that should be fixed now

**Comment by dromer** [comment]
It is not.

**Comment by tl072** [comment]
Confirmed - it is not fixed I have the same compile error after issue #130 compilation issue was solved.

**Comment by shooking** [comment]
Hi @tl072 
Your binutils is too old.
@RomanKubiak has set the build to 2.34 or later.
On a Pi I have 2.32.
So I downloaded the binutils git, installed texinfo, had to modify a file (%lld rather than %ld) and could build latest binutils for Pi, then Ctrlr just builds

Alternative, look for Source/Misc/include
vim libr.h
remove
modify HAVE_BDF_2_34 from 1 to 0
Rebuild
Should work.

**Comment by tl072** [comment]
Hi @shooking many thanks! I just compiled it following what is in issue #100 but I think i am now getting the same crash described in that ticket.

**Comment by shooking** [comment]
Well I am compiling now on Ubuntu 20 LTS.
Will let you know if it works or not.

**Comment by shooking** [comment]
I build cleanon Linux (once I rebuilt the Jucer).
First time round crashed my system.
2nd time aroudn booted .. need to pop out will try later

But I am using Ubuntu 20.x LTS - whatever the non experimental one is 64bit clean install today.

**Comment by keinstein** [comment]
This bug still exists. I ran into it witch up-to-date Debian testing, yesterday.
And it is definitely a bug in libr. For more information I put two links in https://github.com/RomanKubiak/ctrlr/issues/100#issuecomment-777602774 .
